cursor            {{ colors.on_surface.dark.hex }}
cursor_text_color {{ colors.on_primary.dark.hex }}

foreground            {{ colors.on_surface.dark.hex }}
background            {{ colors.term_background.dark.hex }}
selection_foreground  {{ colors.on_secondary_container.dark.hex }}
selection_background  {{ colors.secondary_container.dark.hex }}
url_color             {{ colors.primary.dark.hex }}

color0  {{ colors.term_black.dark.hex }}
color8  {{ colors.term_bright_black.dark.hex }}

color1  {{ colors.term_red.dark.hex }}
color9  {{ colors.term_bright_red.dark.hex }}

color2  {{ colors.term_green.dark.hex }}
color10 {{ colors.term_bright_green.dark.hex }}

color3  {{ colors.term_yellow.dark.hex }}
color11 {{ colors.term_bright_yellow.dark.hex }}

color4  {{ colors.term_blue.dark.hex }}
color12 {{ colors.term_bright_blue.dark.hex }}

color5  {{ colors.term_magenta.dark.hex }}
color13 {{ colors.term_bright_magenta.dark.hex }}

color6  {{ colors.term_cyan.dark.hex }}
color14 {{ colors.term_bright_cyan.dark.hex }}

color7  {{ colors.term_white.dark.hex }}
color15 {{ colors.term_bright_white.dark.hex }}

mark1_foreground {{ colors.on_primary.dark.hex }}
mark1_background {{ colors.primary.dark.hex }}
mark2_foreground {{ colors.on_secondary.dark.hex }}
mark2_background {{ colors.secondary.dark.hex }}
mark3_foreground {{ colors.on_tertiary.dark.hex }}
mark3_background {{ colors.tertiary.dark.hex }}

active_tab_foreground   {{ colors.on_primary.dark.hex }}
active_tab_background   {{ colors.primary.dark.hex }}
inactive_tab_foreground {{ colors.on_surface_variant.dark.hex }}
inactive_tab_background {{ colors.surface_container_high.dark.hex }}

active_border_color   {{ colors.primary.dark.hex }}
inactive_border_color {{ colors.surface_variant.dark.hex }}
