.pragma library

function getNotch() { return "notch" }
function getCircle() { return "circle" }
function getSquare() { return "square" }
function getSlanted() { return "slanted" }
function getArch() { return "arch" }
function getFan() { return "fan" }
function getArrow() { return "arrow" }
function getSemiCircle() { return "semiCircle" }
function getOval() { return "oval" }
function getPill() { return "pill" }
function getTriangle() { return "triangle" }
function getDiamond() { return "diamond" }
function getClamShell() { return "clamShell" }
function getPentagon() { return "pentagon" }
function getGem() { return "gem" }
function getSunny() { return "sunny" }
function getVerySunny() { return "verySunny" }
function getCookie4Sided() { return "cookie4" }
function getCookie6Sided() { return "cookie6" }
function getCookie7Sided() { return "cookie7" }
function getCookie9Sided() { return "cookie9" }
function getCookie12Sided() { return "cookie12" }
function getGhostish() { return "ghostish" }
function getClover4Leaf() { return "clover4" }
function getClover8Leaf() { return "clover8" }
function getBurst() { return "burst" }
function getSoftBurst() { return "softBurst" }
function getBoom() { return "boom" }
function getSoftBoom() { return "softBoom" }
function getFlower() { return "flower" }
function getPuffy() { return "puffy" }
function getPuffyDiamond() { return "puffyDiamond" }
function getPixelCircle() { return "pixelCircle" }
function getPixelTriangle() { return "pixelTriangle" }
function getBun() { return "bun" }
function getHeart() { return "heart" }
function getCookie4ExpandedTopLeft() { return "cookie4ExpandedTL" }
